/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowInstancesIndexRouteImport } from './routes/workflowInstances/index'
import { Route as WorkflowInstancesInstanceIdRouteImport } from './routes/workflowInstances/$instanceId'
import { Route as AdminWorkflowWorkflowIdFormsIndexRouteImport } from './routes/admin/workflow/$workflowId/forms/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowInstancesIndexRoute = WorkflowInstancesIndexRouteImport.update({
  id: '/workflowInstances/',
  path: '/workflowInstances/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowInstancesInstanceIdRoute =
  WorkflowInstancesInstanceIdRouteImport.update({
    id: '/workflowInstances/$instanceId',
    path: '/workflowInstances/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminWorkflowWorkflowIdFormsIndexRoute =
  AdminWorkflowWorkflowIdFormsIndexRouteImport.update({
    id: '/admin/workflow/$workflowId/forms/',
    path: '/admin/workflow/$workflowId/forms/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workflowInstances/$instanceId': typeof WorkflowInstancesInstanceIdRoute
  '/workflowInstances': typeof WorkflowInstancesIndexRoute
  '/admin/workflow/$workflowId/forms': typeof AdminWorkflowWorkflowIdFormsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workflowInstances/$instanceId': typeof WorkflowInstancesInstanceIdRoute
  '/workflowInstances': typeof WorkflowInstancesIndexRoute
  '/admin/workflow/$workflowId/forms': typeof AdminWorkflowWorkflowIdFormsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workflowInstances/$instanceId': typeof WorkflowInstancesInstanceIdRoute
  '/workflowInstances/': typeof WorkflowInstancesIndexRoute
  '/admin/workflow/$workflowId/forms/': typeof AdminWorkflowWorkflowIdFormsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workflowInstances/$instanceId'
    | '/workflowInstances'
    | '/admin/workflow/$workflowId/forms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workflowInstances/$instanceId'
    | '/workflowInstances'
    | '/admin/workflow/$workflowId/forms'
  id:
    | '__root__'
    | '/'
    | '/workflowInstances/$instanceId'
    | '/workflowInstances/'
    | '/admin/workflow/$workflowId/forms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkflowInstancesInstanceIdRoute: typeof WorkflowInstancesInstanceIdRoute
  WorkflowInstancesIndexRoute: typeof WorkflowInstancesIndexRoute
  AdminWorkflowWorkflowIdFormsIndexRoute: typeof AdminWorkflowWorkflowIdFormsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflowInstances/': {
      id: '/workflowInstances/'
      path: '/workflowInstances'
      fullPath: '/workflowInstances'
      preLoaderRoute: typeof WorkflowInstancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflowInstances/$instanceId': {
      id: '/workflowInstances/$instanceId'
      path: '/workflowInstances/$instanceId'
      fullPath: '/workflowInstances/$instanceId'
      preLoaderRoute: typeof WorkflowInstancesInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workflow/$workflowId/forms/': {
      id: '/admin/workflow/$workflowId/forms/'
      path: '/admin/workflow/$workflowId/forms'
      fullPath: '/admin/workflow/$workflowId/forms'
      preLoaderRoute: typeof AdminWorkflowWorkflowIdFormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkflowInstancesInstanceIdRoute: WorkflowInstancesInstanceIdRoute,
  WorkflowInstancesIndexRoute: WorkflowInstancesIndexRoute,
  AdminWorkflowWorkflowIdFormsIndexRoute:
    AdminWorkflowWorkflowIdFormsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
